// Autogenerated from Pigeon (v0.1.23), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTTextureMessage;
@class FLTNetworkImageMessage;

@interface FLTTextureMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * textureId;
@end

@interface FLTNetworkImageMessage : NSObject
@property(nonatomic, copy, nullable) NSString * url;
@property(nonatomic, strong, nullable) NSNumber * width;
@property(nonatomic, strong, nullable) NSNumber * height;
@end

@protocol FLTTextureImageApi
-(nullable FLTTextureMessage *)createTextureImage:(FLTNetworkImageMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)dispose:(FLTTextureMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTTextureImageApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTTextureImageApi> _Nullable api);

NS_ASSUME_NONNULL_END
