analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

  exclude:
    - "**/*.g.dart"
    - "**/*.http_client.dart"
    - "lib/models/**.dart"
    - .history/**
    - test/_data/**
    - test/rules/**
    - lib/account/**
    - lib/res/**

linter:
  rules:
    - avoid_relative_lib_imports
    - avoid_double_and_int_checks
    - avoid_catches_without_on_clauses
    - avoid_classes_with_only_static_members
    - avoid_field_initializers_in_const_classes
    - avoid_null_checks_in_equality_operators
    - avoid_void_async
    - always_use_package_imports
    - await_only_futures
    - camel_case_types
    - camel_case_extensions
    - cancel_subscriptions
    - close_sinks
    - no_duplicate_case_values
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - avoid_catching_errors
    - control_flow_in_finally
    - directives_ordering
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_const_constructors_in_immutables
    - prefer_final_fields
    - prefer_const_declarations
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_int_literals
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_statements
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    - unnecessary_this
    - void_checks
    - library_names
    - file_names
    - library_prefixes
    - curly_braces_in_flow_control_structures
    - slash_for_doc_comments
    - prefer_adjacent_string_concatenation
    - prefer_interpolation_to_compose_strings
    - prefer_collection_literals
    - avoid_function_literals_in_foreach_calls
    - prefer_iterable_whereType
    - prefer_function_declarations_over_variables
    - prefer_equal_for_default_values
    - avoid_init_to_null
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - unnecessary_const
    - use_rethrow_when_possible
    - use_to_and_as_if_applicable
    - one_member_abstracts
    - use_setters_to_change_properties
    - avoid_setters_without_getters
    - avoid_returning_null
    - avoid_returning_this
    - omit_local_variable_types
    - avoid_return_types_on_setters
    - prefer_generic_function_type_aliases
    - avoid_private_typedef_functions
