name: flutter_texture_image
description: Flutter Plugin for displaying inilne texture image with other Flutter widgets on Android, iOS.
version: 0.0.1
homepage: https://github.com/torico-tokyo/flutter_texture_image

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^0.1.21

flutter:
  plugin:
    platforms:
      android:
        package: com.toricotokyo.flutter_texture_image
        pluginClass: FlutterTextureImagePlugin
      ios:
        pluginClass: FlutterTextureImagePlugin
